### ISSUE TITLE
请更新npm仓库的包

### ISSUE THREAD

**Issue by williamnie** [brucewar/egg-elasticsearch#2]
您好，感谢您合并了我的代码，麻烦更新下版本号，然后同步下npm 的仓库，我看您已经合并了代码，麻烦更新到npm

**Comment by brucewar** [comment]
> 您好，感谢您合并了我的代码，麻烦更新下版本号，然后同步下npm 的仓库，我看您已经合并了代码，麻烦更新到npm

不好意思，才发布
