### ISSUE TITLE
ElasticSearch不关闭可能导致的问题.

### ISSUE THREAD

**Issue by schizobulia** [brucewar/egg-elasticsearch#3]
您好，我查看了一下该包的源代码发现在每次使用完es之后并不会执行elasticsearch.close().
此做法在处理实时数据的情况下可能会导致对es连接过多，导致es拒绝访问。

**Comment by brucewar** [comment]
> 您好，我查看了一下该包的源代码发现在每次使用完es之后并不会执行elasticsearch.close().
> 此做法在处理实时数据的情况下可能会导致对es连接过多，导致es拒绝访问。

你好，使用的elasticsearch官方提供的JavaScript API，在egg应用启动的时候，只会初始化一个client，挂载在app对象上。我又去看了下官方文档，好像没有相关的close方法

**Comment by schizobulia** [comment]
官方文档并没有明确指出，是我在实际应用场景中出现的bug(对服务器建立上万次连接,导致es无法连接).
我查看es.js源代码发现他使用完成之后可能并不会马上释放，之后发现Client中提供了close方法。
此处为官方issues中讨论close方法：
1.  https://github.com/elastic/elasticsearch-js/issues/40
2.  https://github.com/elastic/elasticsearch-js/issues/165
注：建议执行close方法，程序中只存在一个Client，该Client不释放是否会导致连接一直存在，对性能存在影响. 
自己写一段执行close的代码： 
https://privatebin.net/?16fb564e6739c45d#H06oIxt/MJbpVFarwehnRDFbfNQwjxTv1x8MLgzhFzI=
